// Website icons from the app tile (resources/icon.html): the Space Grotesk
// Bold "P", outlined to a path so favicons need no web font, on the brand
// gradient. Writes public/icon.svg (rounded), public/icon-maskable.svg
// (full bleed) and PNGs for iOS (apple-touch-icon) and the web manifest.
// Run: node resources/web-icons.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import opentype from 'opentype.js';
import sharp from 'sharp';

const fontFile = readFileSync('node_modules/@fontsource/space-grotesk/files/space-grotesk-latin-700-normal.woff');
const font = opentype.parse(fontFile.buffer.slice(fontFile.byteOffset, fontFile.byteOffset + fontFile.byteLength));

/** The "P" scaled so its outline is `height` tall, centred on (256, 256). */
function pPath(height) {
  const probe = font.getPath('P', 0, 0, 100).getBoundingBox();
  const size = (100 * height) / (probe.y2 - probe.y1);
  const box = font.getPath('P', 0, 0, size).getBoundingBox();
  const x = 256 - (box.x1 + box.x2) / 2;
  const y = 256 - (box.y1 + box.y2) / 2;
  return font.getPath('P', x, y, size).toPathData(1);
}

// CSS linear-gradient(145deg, #2ee3c2, #14c9b6), as in the in-app tile.
const gradient = `<defs><linearGradient id="g" x1="0.21" y1="0.09" x2="0.79" y2="0.91">
    <stop offset="0" stop-color="#2ee3c2"/><stop offset="1" stop-color="#14c9b6"/>
  </linearGradient></defs>`;

const svg = (rx, pHeight, note) => `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512">
  <!-- ${note} Generated by resources/web-icons.mjs. -->
  ${gradient}
  <rect width="512" height="512"${rx ? ` rx="${rx}"` : ''} fill="url(#g)"/>
  <path fill="#0b2e2a" d="${pPath(pHeight)}"/>
</svg>
`;

// Same proportions as the launcher icon (P is 46% of the tile) for the
// full-bleed and maskable versions; the rounded tile matches the splash.
const rounded = svg(128, 0.43 * 512, 'App tile: Space Grotesk Bold "P" on the brand gradient.');
const fullBleed = svg(0, 0.46 * 512, 'Full-bleed app tile for maskable / home-screen use; the P sits inside the safe zone.');
writeFileSync('public/icon.svg', rounded);
writeFileSync('public/favicon.svg', rounded);
writeFileSync('public/icon-maskable.svg', fullBleed);

const png = (src, size, out) => sharp(Buffer.from(src)).resize(size, size).png().toFile(out);
// iOS ignores SVG touch icons and rounds the corners itself: full bleed, opaque.
await sharp(Buffer.from(fullBleed)).resize(180, 180).flatten({ background: '#2ee3c2' }).png().toFile('public/apple-touch-icon.png');
await png(rounded, 192, 'public/icon-192.png');
await png(rounded, 512, 'public/icon-512.png');
await png(fullBleed, 512, 'public/icon-maskable-512.png');
console.log('web icons written');
